# Generated by Django 5.0.1 on 2024-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_name', models.CharField(max_length=100)),
                ('work_time', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('status', models.SmallIntegerField(choices=[(1, 'Ochiq'), (2, 'Yopiq')], default=1)),
            ],
        ),
    ]
