# Generated by Django 5.0.3 on 2024-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Ochiq'), (2, 'Yopiq')]),
        ),
    ]
